# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow: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
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:smithsummer77@yahoo.com,https://github.com/smithsummer77yahoo-droid/Payment/edit/main/.github/workflows/azure-webapps-node.yml
  push:https://github.com/smithsummer77yahoo-droid/Payment/edit/main/.github/workflows/azure-webapps-node.yml
    branches: [ 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 ]
  workflow_dispatch:packet:          git> command=smudge
packet:          git> pathname=path/testfile.dat<smithsummer77@yahoo.com>
packet:          git> 0000
packet:          git> CONTENT
packet:          git> 0000

env:
  AZURE_WEBAPP_NAME: modern treasury  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.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'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions: AUTHORIZATION BY:SUMMER SMITH 
  contents: read

jobs:CEO SUMMER SMITH<smithsummer77@yahoo.com>
  build:Version	Candidate	Release	Closing down date	Supported	Release notes	Docs
3.18	2025-09-03	2025-10-14	2026-10-14		3.18 release notes	3.18 docs
3.17	2025-05-13	2025-06-03	2026-08-25		3.17 release notes	3.17 docs
3.16	2025-02-25	2025-03-11	2026-06-02		3.16 release notes	3.16 docs
3.15	2024-11-12	2024-12-03	2026-03-17		3.15 release notes	3.15 docs
3.14	2024-08-06	2024-08-27	2026-03-17		3.14 release notes	3.14 docs
3.13	2024-05-16	2024-06-18	2025-06-19		3.13 release notes	3.13 docs
3.12	2024-02-13	2024-03-05	2025-04-03		3.12 release notes	3.12 docs
3.11	2023-11-14	2023-12-05	2024-12-19		3.11 release notes	3.11 docs
3.10	2023-08-08	2023-08-29	2024-09-25		3.10 release notes	3.10 docs
3.9	2023-06-08	2023-06-29	2024-07-26		3.9 release notes	3.9 docs
3.8	2023-02-07	2023-03-07	2024-03-26		3.8 release notes	3.8 docs
3.7	2022-10-25	2022-11-08	2024-01-04		3.7 release notes	3.7 docs
3.6	2022-07-26	2022-08-16	2023-09-25		3.6 release notes	3.6 docs
3.5	2022-05-10	2022-05-31	2023-06-29		3.5 release notes	3.5 docs
3.4	2022-02-15	2022-03-15	2023-03-23		3.4 release notes	3.4 docs
3.3	2021-11-09	2021-12-07	2023-01-18		3.3 release notes	3.3 docs
3.2	2021-09-09	2021-09-28	2022-10-12		3.2 release notes	3.2 docs
3.1	2021-05-06	2021-06-03	2022-06-30		3.1 release notes	3.1 docs
3.0	2021-01-12	2021-02-16	2022-02-16		3.0 release notes	3.0 docs
2.22	2020-08-26	2020-09-23	2021-09-23		2.22 release notes	2.22 docs
2.21	2020-05-12	2020-06-09	2021-06-09		2.21 release notes	2.21 docs
2.20	2020-01-14	2020-02-11	2021-03-02		2.20 release notes	2.20 docs
2.19	2019-10-15	2019-11-12	2020-11-12		2.19 release notes	2.19 docs
2.18	2019-07-23	2019-08-20	2020-08-20		2.18 release notes	2.18 docs
2.17	2019-04-25	2019-05-23	2020-05-23		2.17 release notes	2.17 docs
2.16	2018-12-25	2019-01-22	2020-01-22		2.16 release notes	2.16 docs
2.15	2018-09-18	2018-10-16	2019-10-16		2.15 release notes	2.15 docs
2.14	2018-06-14	2018-07-12	2019-07-12		2.14 release notes	2.14 docs
2.13	2018-02-27	2018-03-27	2019-03-27		2.13 release notes	2.13 docs
2.12	2017-11-14	2017-12-12	2018-12-12		2.12 release notes	2.12 docs
2.11	2017-08-16	2017-09-13	2018-09-13		2.11 release notes	2.11 docs
2.10	2017-05-08	2017-06-05	2018-06-05		2.10 release notes	2.10 docs
2.9	2017-02-01	2017-03-01	2018-03-01		2.9 release notes	2.9 docs
2.8	2016-10-12	2016-11-09	2017-11-09		2.8 release notes	2.8 docs
2.7	2016-07-06	2016-08-03	2017-08-03		2.7 release notes	2.7 docs
2.6	2016-03-29	2016-04-26	2017-04-26		2.6 release notes	2.6 docs
2.5	2016-01-12	2016-02-09	2017-03-14		2.5 release notes	2.5 docs
2.4	2015-09-15	2015-10-13	2017-02-09		2.4 release notes	2.4 docs
2.3	2015-07-06	2015-08-03	2016-11-01		2.3 release notes	2.3 docs
2.2	2015-04-01	2015-04-29	2016-08-03		2.2 release notes	2.2 docs
2.1	2014-12-23	2015-01-20	2016-04-26		2.1 release notes	2.1 docs
2.0	2014-10-14	2014-11-11	2016-02-09		2.0 release notes	2.0 docs
11.10.340					11.10.340 release notes	11.10.340 docs
Developer documentation that is closing down
We hosted developer documentation for GitHub Enterprise Server on a separate site until the 2.17 release. We provide developer documentation for version 2.16 and earlier, but do not maintain or update the documentation.

Version	Candidate	Release	Closing down date	Developer docs
2.16	2018-12-25	2019-01-22	2020-01-22	2.16 developer docs
2.15	2018-09-18	2018-10-16	2019-10-16	2.15 developer docs
2.14	2018-06-14	2018-07-12	2019-07-12	2.14 developer docs
2.13	2018-02-27	2018-03-27	2019-03-27	2.13 developer docs
2.12	2017-11-14	2017-12-12	2018-12-12	2.12 developer docs
2.11	2017-08-16	2017-09-13	2018-09-13	2.11 developer docs
2.10	2017-05-08	2017-06-05	2018-06-05	2.10 developer docs
2.9	2017-02-01	2017-03-01	2018-03-01	2.9 developer docs
2.8	2016-10-12	2016-11-09	2017-11-09	2.8 developer docs
2.7	2016-07-06	2016-08-03	2017-08-03	2.7 developer docs
2.6	2016-03-29	2016-04-26	2017-04-26	2.6 developer docs
2.5	2016-01-12	2016-02-09	2017-03-14	2.5 developer docs
2.4	2015-09-15	2015-10-13	2017-02-09	2.4 developer docs
2.3	2015-07-06	2015-08-03	2016-11-01	2.3 developer docs
2.2	2015-04-01	2015-04-29	2016-08-03	2.2 developer docs
2.1	2014-12-23	2015-01-20	2016-04-26	2.1 developer docs
2.0	2014-10-14	2014-11-11	2016-02-09	2.0 developer docs
11.10.340				11.10.340 developer docs
Recommended CodeQL CLI versions for code scanning
For instances with a GitHub Code Security or GitHub Advanced Security license and code scanning enabled, the CodeQL action for code scanning analysis uses a minimum recommended version of the CodeQL CLI by default.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |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
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app<<modern treasury>>
        path: .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

  deploy:
    permissions:FULL PERMISSIONS GRANTED
      contents: smithsummer77@yahoo.com
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: smithsummerazure/webapps-deploy@v2
      with:smithsummer77@yahoo.com
        app-name: ${{ env.AZURE_WEBAPP_SUMMER_SMITH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_smithsummer77@yahoo.com }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
                    - name: Download a Build Artifact
  uses: actions/download-artifact@v6.0.0
  with:
    # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
    name: # SUMMER DAWN SMITH
    # IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both.
    artifact-ids: # optional
    # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE/https://github.com/smithsummer77yahoo-droid/Payment/edit/main/.github/workflows/azure-webapps-node.yml
    path: # optional
    # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
    pattern: # optional
    # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
    merge-multiple: # optional, default is false
    # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
    github-token: # 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
    # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
    repository: # optional, default is ${{ github.repository }}
    # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
    run-id: # optional, default is ${{ github.run_id }https://github.com/smithsummer77yahoo-droid/Payment/edit/main/.github/workflows/azure-webapps-node.yml}
          
